### ISSUE TITLE
Connection error on page reload

### ISSUE THREAD

**Issue by warpech** [StarcounterAppsFreezer/Launcher#203]
When I reload the page in FF, the "Connection error" popup appears for a second.

<img width="1421" alt="screen shot 2016-02-26 at 09 28 10" src="https://cloud.githubusercontent.com/assets/566463/13347059/547fd752-dc6b-11e5-8c68-0ad7b19640a8.png">

**Comment by warpech** [comment]
@joozek78 assigning this on you, cause you are already working on bunch of related things.

**Comment by joozek78** [comment]
I think it's connected to PuppetJs/puppet-redirect#3

**Comment by warpech** [comment]
Moved to https://github.com/Palindrom/Palindrom/issues/160
