### ISSUE TITLE
Should Launcher be aware of sign in app?

### ISSUE THREAD

**Issue by tomalec** [StarcounterAppsFreezer/Launcher#88]
After discussing with @andwah on Hangouts we decided to keep it tracked somewhere here.

It started with an idea of making a full page login/signup form like [one from Google](https://accounts.google.com/AddSession) to which user will be redirected in case he tried to access forbidden URL.

Currently we agreed that any app in case of attempt to access to forbidden resources, instead of returning  its page/tile/whatever, returns single line of HTML with `<juicy-redirect>`, that redirects (hard or not?) to Sign-in App url (as for now each App may and need to choose it's own Auth app, and hard-codes the path).

The question is this page should look and be handled by Launcher?
## 1. The page should be totally in control of SignIn App and contain only log-in form.
1. That means in fact `/signinapp/signin`, and no Launcher at all
#### Pros:
- looks nice
#### Cons:
- Hey! We wanded Polyjuice system with everything working together, not a set of standalone freaks!
1. Or at least `/launcher/sigininapp/signin`, and Launcher that fallbacks to [microLauncher](https://github.com/Polyjuice/microLauncher), so just forward whatever it gets, and wraps with PuppetJS and namespaces.
#### Pros:
- looks nice
#### Cons:
- URL pattern for "`/launcher/whatever/whatever/` - which was not yet registered" may be difficult
- Not that freaky but still..
## 2. The page should contain only log-in form, but Launcher should be in charge

 That means Launcher would need a specific place (a page, or place in main template), for such authentication specific things.
#### Pros:
- looks nice
#### Cons:
- requires specific code in Launcher, that may end up app specyfic, what is extremely bad.
- and making authorization specific, but app agnostic layout, seems extremely hard
## 3. Put it into SignInApp workspace

 There will be no specific place, just workspace as for any other app, which may be change according to Launcher UI/UX. In our case there will be menu on left, and topbar with probably login widget on top.
#### Pros:
- no code needed :)
- signin app ends as any other app, so no additional concept to keep in mind, explain, no magic at all (no magic may be harder to explain ;) ),
#### Cons:
- does not look nice
- login form may be duplicated

@Starcounter-Jack, @warpech  any comments, ideas?

**Comment by miyconst** [comment]
@tomalec, can this issue be closed as SignIn app has already been developed and used in UserAdmin app?

**Comment by warpech** [comment]
This issue cannot be closed, because the question is still valid: 

Should an app (UserAdmin) redirect to a login form which comes from another apps (SignIn, GoogleSignIn)? If yes then how?

**Comment by miyconst** [comment]
As I proposed long time ago, I think that UserAdmin app should redirect to `/launcher/signin` and Launcher should use PolyjuiceMap the same as it does for menu and signin section to display sign in forms from all of the available apps.

**Comment by miyconst** [comment]
Another input:

Right now we have this [map](https://github.com/StarcounterSamples/SignIn/blob/master/src/SignIn/Api/MainHandlers.cs#L62):

```cs
UriMapping.Map("/signin/signinuser", "/sc/mapping/userform");
```

Which maps sign in form to `/sc/mapping/userform` and in the apps which require authentication do like this:

```cs
if (hasAccess) {
    this.Partial = Self.GET("/ProtectedUrl");
} else {
    this.Partial = Self.GET("/sc/mapping/userform");
}
```

This pattern is used in Website, Content, Warehouse, SweOffshore apps.

**Comment by warpech** [comment]
The pattern, which is an elaboration of the above comment by @miyconst, is now being explained in https://github.com/Starcounter/Docs/issues/113
